"""Learning, Briefing, and ImprovementMetric ORM models.

Models for Sophia's learning persistence pipeline: structured learnings
from cycle outcomes, operator feedback, and performance signals. Also
includes briefing persistence and structured business intelligence entries.

All models inherit from Base and TimestampMixin. No cross-client ORM
relationships -- data isolation enforced at the service layer.
"""

from datetime import datetime
from enum import Enum as PyEnum
from typing import Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from sophia.db.base import Base, TimestampMixin


class LearningType(str, PyEnum):
    """Categories of structured learnings Sophia persists."""

    CONTENT = "content"
    VOICE = "voice"
    RESEARCH = "research"
    STRATEGY = "strategy"
    OPERATOR_FEEDBACK = "operator_feedback"


class InsightCategory(str, PyEnum):
    """Domain categories for structured business insights."""

    BUSINESS = "business"
    INDUSTRY = "industry"
    COMPETITORS = "competitors"
    CUSTOMERS = "customers"
    PRODUCT_SERVICE_OFFER = "product_service_offer"
    SALES_PROCESS = "sales_process"


class Learning(TimestampMixin, Base):
    """A structured learning extracted from cycle outcomes or operator feedback.

    Each learning is a distilled fact, pattern, or insight -- never a raw
    conversation transcript. Learnings compound over time and can be
    superseded when new information contradicts or refines older entries.

    Supersession chain: old learning -> is_superseded=True, superseded_by_id
    points to the new learning that replaced it.
    """

    __tablename__ = "learnings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    client_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("clients.id"), nullable=False, index=True
    )
    learning_type: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True
    )  # Uses LearningType enum values
    source: Mapped[str] = mapped_column(
        String(100), nullable=False
    )  # e.g., "cycle_approval", "operator_chat", "performance_signal"
    content: Mapped[str] = mapped_column(
        Text, nullable=False
    )  # The structured learning itself (NOT raw conversation)
    confidence: Mapped[float] = mapped_column(
        Float, default=0.8, nullable=False
    )
    is_superseded: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )
    superseded_by_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("learnings.id"), nullable=True
    )
    cycle_run_id: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True
    )  # FK to cycle_runs.id (nullable -- learnings can come from outside cycles)

    __table_args__ = (
        Index("ix_learnings_client_type", "client_id", "learning_type"),
    )


class BusinessInsight(TimestampMixin, Base):
    """Structured business insight extracted from operator conversations (LRNG-04).

    Each entry is a concrete fact statement about a client's business,
    with source attribution and confidence level. Used to build progressive
    client intelligence that compounds over time.
    """

    __tablename__ = "business_insights"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    client_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("clients.id"), nullable=False, index=True
    )
    category: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # Uses InsightCategory enum values
    fact_statement: Mapped[str] = mapped_column(
        Text, nullable=False
    )  # e.g., "Shane is expanding into commercial HVAC"
    source_attribution: Mapped[str] = mapped_column(
        String(200), nullable=False
    )  # e.g., "operator conversation 2026-02-26"
    confidence: Mapped[float] = mapped_column(
        Float, default=0.8, nullable=False
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False
    )

    __table_args__ = (
        Index("ix_business_insights_client_category", "client_id", "category"),
    )


class Briefing(TimestampMixin, Base):
    """Persisted briefing content (daily standup or weekly strategic).

    Content is stored as JSON-serialized string for flexibility.
    Generated by scheduled jobs, not inside per-client cycles.
    """

    __tablename__ = "briefings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    briefing_type: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # "daily" or "weekly"
    content_json: Mapped[str] = mapped_column(
        Text, nullable=False
    )  # JSON-serialized briefing content
    generated_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now()
    )
